### PR TITLE
Update to latest beta

### PR DESCRIPTION
**Pull request by KyleAMathews**
Everything seems happy now 👍

### CODE REVIEW

**Comment by bvaughn** [comment]
Oh, nice! This fixes the empty markdown files issue?

**Comment by bvaughn** [comment]
I'm guessing not. Running a fresh `yarn install` with this `package.json` change, I still see a few
```
The new node didn't pass validation
ValidationError: child "internal" fails because [child "content" fails because ["content" is not allowed to be empty]]
```
and
```
Calling "createNodeField" with "fieldValue" is deprecated. Use "value" instead
success source and transform nodes — 1.258 s
⠂ building schemaUNHANDLED REJECTION TypeError: Cannot read property 'internal' of undefined
    at /Users/bvaughn/Documents/git/react/www/node_modules/gatsby/dist/schema/build-node-types.js:175:26
    at arrayAggregator (/Users/bvaughn/Documents/git/react/www/node_modules/lodash/lodash.js:518:34)
    at Function.groupBy (/Users/bvaughn/Documents/git/react/www/node_modules/lodash/lodash.js:4862:16)
    at /Users/bvaughn/Documents/git/react/www/node_modules/lodash/lodash.js:4379:28
    at arrayReduce (/Users/bvaughn/Documents/git/react/www/node_modules/lodash/lodash.js:704:21)
    at baseWrapperValue (/Users/bvaughn/Documents/git/react/www/node_modules/lodash/lodash.js:4378:14)
    at LodashWrapper.wrapperValue (/Users/bvaughn/Documents/git/react/www/node_modules/lodash/lodash.js:9067:14)
    at createNodeFields (/Users/bvaughn/Documents/git/react/www/node_modules/gatsby/dist/schema/build-node-types.js:176:16)
    at fields (/Users/bvaughn/Documents/git/react/www/node_modules/gatsby/dist/schema/build-node-types.js:86:26)
    at resolveThunk (/Users/bvaughn/Documents/git/react/www/node_modules/graphql/type/definition.js:167:40)
    at defineFieldMap (/Users/bvaughn/Documents/git/react/www/node_modules/graphql/type/definition.js:345:18)
    at GraphQLObjectType.getFields (/Users/bvaughn/Documents/git/react/www/node_modules/graphql/type/definition.js:306:44)
    at typeMapReducer (/Users/bvaughn/Documents/git/react/www/node_modules/graphql/type/schema.js:206:25)
    at /Users/bvaughn/Documents/git/react/www/node_modules/graphql/type/schema.js:216:20
    at Array.forEach (native)
    at typeMapReducer (/Users/bvaughn/Documents/git/react/www/node_modules/graphql/type/schema.js:207:27)
```
and then "_building schema_" just kind of hangs.

**Comment by KyleAMathews** [comment]
Hmm it just works for me... I added my yarn.lock and and added `yarn &&` in front of the various npm scripts. Try running `npm run dev` on this branch?

**Comment by bvaughn** [comment]
Hm, maybe `npm run dev` was the problem then. :)

**Pull request closed without merging**
